import { useEffect, useMemo, useState, type Dispatch, type SetStateAction } from 'react';
import axios from 'axios';
import type { Employee, Project, TaskPriority } from '../../types/pm';
import { TASK_PRIORITIES } from '../../types/pm';

type Ticket = {
  uid: string;
  title: string;
  description: string;
  level: string;
  estimate_hours: number | '';
  priority: TaskPriority;
  assigneeId: string;
  dueDate: string;
  state: 'draft' | 'pushed' | 'failed';
  error?: string | null;
  autoGenerated?: boolean;
  sourceIndex?: number;
};
type Summary = { id: number; title: string; status: string; total: number; pushed: number; project_id: string | null; updated_at: string | null };
type Draft = Summary & { brief: string; tickets: Ticket[] };
type RequirementBlock = { title: string; description: string; sourceIndex: number };

const input = 'rounded-md border border-slate-200 px-2 py-1.5 text-sm focus:border-slate-400 focus:outline-none';
const makeUid = () => `draft-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
const blank = (title = '', description = '', autoGenerated = false, sourceIndex?: number): Ticket => ({ uid: makeUid(), title, description, level: 'intern', estimate_hours: '', priority: 'Medium', assigneeId: '', dueDate: '', state: 'draft', error: null, autoGenerated, sourceIndex });
const errText = (e: any, fallback: string) => e?.response?.data?.message || e?.response?.data?.error || fallback;

function requirementBlocks(brief: string | null | undefined): RequirementBlock[] {
  const normalized = (brief ?? '').replace(/\r/g, '').trim();
  if (!normalized) return [];

  return normalized
    .split(/\n\s*\n+/)
    .map((block, sourceIndex) => {
      const lines = block
        .split('\n')
        .map((line) => line.trim())
        .filter(Boolean)
        .filter((line) => !/^[-_=]{3,}\s*(?:space)?\s*[-_=]{3,}$/i.test(line));

      if (!lines.length) return null;

      const title = lines[0]
        .replace(/^[-*•–—]\s+/, '')
        .replace(/^\d+[.)]\s+/, '')
        .trim();

      return { title: title || 'Untitled ticket', description: lines.slice(1).join('\n'), sourceIndex };
    })
    .filter((block): block is RequirementBlock => Boolean(block));
}

function normalizedText(value: string): string {
  return (value ?? '').replace(/\s+/g, ' ').trim().toLowerCase();
}

function ticketTitle(requirement: string): string {
  const cleaned = (requirement ?? '').replace(/\s+/g, ' ').trim();
  if (!cleaned) return 'Untitled ticket';
  return cleaned.length > 140 ? `${cleaned.slice(0, 137).trim()}…` : cleaned;
}

function buildAutomaticTickets(brief: string | null | undefined, existing: Ticket[] | null | undefined): Ticket[] {
  const currentTickets = Array.isArray(existing) ? existing : [];
  const blocks = requirementBlocks(brief).slice(0, 30);
  const pushed = currentTickets.filter((t) => t.state === 'pushed');
  const manual = currentTickets.filter((t) => t.state !== 'pushed' && !t.autoGenerated);
  const previousAuto = currentTickets.filter((t) => t.state !== 'pushed' && t.autoGenerated);
  const used = new Set<string>();

  const generated = blocks.map((block) => {
    const byTitle = previousAuto.find((t) => !used.has(t.uid) && normalizedText(t.title) === normalizedText(block.title));
    const byIndex = previousAuto.find((t) => !used.has(t.uid) && t.sourceIndex === block.sourceIndex);
    const previous = byTitle ?? byIndex;

    if (previous) {
      used.add(previous.uid);
      return { ...previous, title: ticketTitle(block.title), description: block.description, autoGenerated: true, sourceIndex: block.sourceIndex, state: 'draft' as const, error: null };
    }

    return blank(ticketTitle(block.title), block.description, true, block.sourceIndex);
  });

  return [...pushed, ...manual, ...generated].slice(0, 30);
}

function normalizeLoadedTickets(tickets: Ticket[]): Ticket[] {
  let generatedIndex = 0;
  return (Array.isArray(tickets) ? tickets : []).map((ticket) => {
    if (!ticket.autoGenerated || ticket.state === 'pushed') return ticket;
    const sourceIndex = ticket.sourceIndex ?? generatedIndex++;
    return { ...ticket, sourceIndex, autoGenerated: true };
  });
}

type EditorProps = {
  draft: Draft;
  projects: Project[];
  employees: Employee[];
  newProject: boolean;
  newProjectName: string;
  currentProject?: Project;
  saving: boolean;
  converting: boolean;
  setDraft: Dispatch<SetStateAction<Draft | null>>;
  setNewProject: Dispatch<SetStateAction<boolean>>;
  setNewProjectName: Dispatch<SetStateAction<string>>;
  saveDraft: () => Promise<void>;
  verify: () => Promise<void>;
  convert: () => Promise<void>;
  selectOrCreateProject: () => Promise<string | null>;
};

function DraftEditor({ draft, projects, employees, newProject, newProjectName, currentProject, saving, converting, setDraft, setNewProject, setNewProjectName, saveDraft, verify, convert, selectOrCreateProject }: EditorProps) {
  const updateTicket = (uid: string, patch: Partial<Ticket>) => setDraft((d) => {
    if (!d) return d;
    const breaksAutomaticSync = 'title' in patch || 'description' in patch;
    return { ...d, tickets: d.tickets.map((t) => t.uid === uid ? { ...t, ...patch, ...(breaksAutomaticSync ? { autoGenerated: false, sourceIndex: undefined } : {}) } : t), status: d.status === 'verified' ? 'draft' : d.status };
  });
  const addTicket = () => setDraft((d) => d ? { ...d, tickets: [...d.tickets, blank()], status: d.status === 'verified' ? 'draft' : d.status } : d);
  const removeTicket = (uid: string) => setDraft((d) => d ? { ...d, tickets: d.tickets.filter((t) => t.uid !== uid), status: d.status === 'verified' ? 'draft' : d.status } : d);

  return <div className="border-t border-slate-200 bg-slate-50 px-4 py-4">
    <div className="rounded-md border border-slate-200 bg-white p-3">
      <div className="mb-2 text-xs font-semibold text-slate-700">Project</div>
      {!newProject ? <div className="flex flex-col gap-2 md:flex-row">
        <select className={`${input} flex-1`} value={draft.project_id || ''} onChange={(e) => setDraft((d) => d ? { ...d, project_id: e.target.value || null } : d)}>
          <option value="">Select existing project…</option>{projects.map((p) => <option key={p._id} value={p._id}>{p.name}</option>)}
        </select>
        <button onClick={() => setNewProject(true)} className="rounded-md border border-slate-300 bg-white px-3 py-1.5 text-xs font-medium">+ New project</button>
      </div> : <div className="flex flex-col gap-2 md:flex-row">
        <input className={`${input} flex-1`} value={newProjectName} onChange={(e) => setNewProjectName(e.target.value)} placeholder="New project name" />
        <button onClick={selectOrCreateProject} className="rounded-md bg-slate-900 px-3 py-1.5 text-xs font-medium text-white">Create project</button>
        <button onClick={() => { setNewProject(false); setNewProjectName(''); }} className="text-xs text-slate-500">Cancel</button>
      </div>}
      {currentProject && <div className="mt-1 text-[11px] text-slate-400">Ticket destination: <span className="font-medium text-slate-600">{currentProject.name}</span></div>}
    </div>

    <div className="mt-3 rounded-md border border-slate-200 bg-white p-3">
      <label className="mb-1 block text-xs font-semibold text-slate-700">Heading</label>
      <input className={`${input} w-full`} value={draft.title} onChange={(e) => setDraft((d) => d ? { ...d, title: e.target.value, status: d.status === 'verified' ? 'draft' : d.status } : d)} placeholder="Brief heading" />
      <label className="mb-1 mt-3 block text-xs font-semibold text-slate-700">Requirements</label>
      <textarea className={`${input} min-h-40 w-full`} value={draft.brief} onChange={(e) => setDraft((d) => d ? { ...d, brief: e.target.value, status: d.status === 'verified' ? 'draft' : d.status } : d)} placeholder={'Write requirements using one blank line between tickets.\n\n- Ticket 1 requirement / title\n  Supporting requirement detail\n  More detail\n\n- Ticket 2 requirement / title\n  Supporting requirement detail'} />
      <div className="mt-2 text-[11px] text-slate-400">Rule: one blank line separates tickets. The first line of each block is the ticket title; every following line is its description. A leading “-” is optional.</div>
    </div>

    <div className="mt-3 flex flex-wrap items-center gap-2">
      <button onClick={saveDraft} disabled={saving} className="rounded-md border border-slate-300 bg-white px-3 py-1.5 text-xs font-medium">{saving ? 'Saving…' : 'Save draft'}</button>
      <button onClick={verify} className="rounded-md border border-slate-300 bg-white px-3 py-1.5 text-xs font-medium">{draft.status === 'verified' ? 'Unverify' : 'Verify brief'}</button>
      <span className="text-xs text-slate-500">Status: {draft.status}</span>
    </div>

    <div className="mt-5 rounded-md border border-slate-200 bg-white p-3">
      <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
        <div><div className="text-xs font-semibold text-slate-700">Tickets to create</div><div className="text-[11px] text-slate-400">Tickets follow the blank-line requirement blocks. Edit a title/description to make that ticket manual; priority, assignee, estimate, and due date remain editable without breaking the requirement link.</div></div>
        <button onClick={addTicket} className="text-xs font-medium text-slate-700 hover:underline">+ Add ticket</button>
      </div>
      {!draft.tickets.length && <div className="rounded border border-dashed border-slate-200 px-3 py-5 text-center text-xs text-slate-400">Start typing requirements above and tickets will appear automatically.</div>}
      <div className="space-y-3">
        {draft.tickets.map((t, i) => <div key={t.uid} className="rounded-md border border-slate-200 p-3">
          <div className="mb-2 flex items-center justify-between"><span className="text-xs font-semibold text-slate-600">Ticket {i + 1}{t.state === 'pushed' ? ' · Created' : t.state === 'failed' ? ' · Failed' : ''}{t.autoGenerated ? ' · Auto' : ''}</span><button onClick={() => removeTicket(t.uid)} className="text-xs text-rose-600 hover:underline">Delete</button></div>
          <div className="grid gap-2 md:grid-cols-2">
            <input className={input} value={t.title} onChange={(e) => updateTicket(t.uid, { title: e.target.value, state: 'draft' })} placeholder="Ticket title" />
            <select className={input} value={t.priority} onChange={(e) => updateTicket(t.uid, { priority: e.target.value as TaskPriority, state: 'draft' })}>{TASK_PRIORITIES.map((p) => <option key={p}>{p}</option>)}</select>
            <textarea className={`${input} min-h-20 md:col-span-2`} value={t.description} onChange={(e) => updateTicket(t.uid, { description: e.target.value, state: 'draft' })} placeholder="Description / acceptance notes" />
            <select className={input} value={t.assigneeId} onChange={(e) => updateTicket(t.uid, { assigneeId: e.target.value, state: 'draft' })}><option value="">Select assignee…</option>{employees.map((e) => <option key={e.employeeId} value={e.employeeId}>{e.name}</option>)}</select>
            <input className={input} type="number" min="0" step="0.5" value={t.estimate_hours} onChange={(e) => updateTicket(t.uid, { estimate_hours: e.target.value === '' ? '' : Number(e.target.value), state: 'draft' })} placeholder="Estimate hours" />
            <input className={input} type="date" value={t.dueDate} onChange={(e) => updateTicket(t.uid, { dueDate: e.target.value, state: 'draft' })} />
            {t.error && <div className="text-xs text-rose-600 md:col-span-2">{t.error}</div>}
          </div>
        </div>)}
      </div>
      <div className="mt-4 flex flex-wrap items-center gap-2 border-t border-slate-100 pt-3"><button onClick={convert} disabled={converting} className="rounded-md bg-slate-900 px-3 py-1.5 text-xs font-medium text-white disabled:opacity-50">{converting ? 'Converting…' : 'Convert to tickets'}</button><span className="text-[11px] text-slate-400">Only tickets not already marked Created are sent.</span></div>
    </div>
  </div>;
}

export default function PmDraftsPanelV2() {
  const [drafts, setDrafts] = useState<Summary[]>([]);
  const [draft, setDraft] = useState<Draft | null>(null);
  const [openId, setOpenId] = useState<number | null>(null);
  const [projects, setProjects] = useState<Project[]>([]);
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [newProject, setNewProject] = useState(false);
  const [newProjectName, setNewProjectName] = useState('');
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [converting, setConverting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function load() {
    setLoading(true);
    try {
      const [d, p, e] = await Promise.all([
        axios.get<{ drafts: Summary[] }>('/pm/drafts'),
        axios.get<{ projects: Project[] }>('/pm/projects'),
        axios.get<{ employees: Employee[] }>('/pm/employees'),
      ]);
      setDrafts(d.data.drafts); setProjects(p.data.projects); setEmployees(e.data.employees);
    } catch (e) { setError(errText(e, "Couldn't load saved briefs.")); }
    finally { setLoading(false); }
  }

  useEffect(() => { load(); }, []);

  useEffect(() => {
    if (!draft) return;
    const timer = window.setTimeout(() => {
      setDraft((current) => {
        if (!current) return current;
        const nextTickets = buildAutomaticTickets(current.brief, current.tickets);
        const oldSignature = current.tickets.map((t) => `${t.uid}:${t.title}:${t.description}:${t.sourceIndex ?? ''}:${t.autoGenerated ? 'a' : 'm'}`).join('|');
        const newSignature = nextTickets.map((t) => `${t.uid}:${t.title}:${t.description}:${t.sourceIndex ?? ''}:${t.autoGenerated ? 'a' : 'm'}`).join('|');
        if (oldSignature === newSignature) return current;
        return { ...current, tickets: nextTickets, status: current.status === 'verified' ? 'draft' : current.status };
      });
    }, 300);
    return () => window.clearTimeout(timer);
  }, [draft?.brief]);

  const currentProject = useMemo(() => projects.find((p) => p._id === draft?.project_id), [projects, draft?.project_id]);

  async function openDraft(id: number) {
    if (openId === id) { setOpenId(null); setDraft(null); return; }
    try {
      const { data } = await axios.get<{ draft: Draft }>(`/pm/drafts/${id}`);
      const loaded = data.draft;
      setDraft({ ...loaded, brief: loaded.brief ?? '', tickets: normalizeLoadedTickets(loaded.tickets ?? []) });
      setOpenId(id); setNewProject(false); setError(null);
    } catch (e) { setError(errText(e, "Couldn't open that brief.")); }
  }

  function newDraft() {
    setDraft({ id: 0, title: '', brief: '', status: 'draft', total: 0, pushed: 0, project_id: null, updated_at: null, tickets: [] });
    setOpenId(0); setNewProject(false); setError(null);
  }

  async function saveDraft() {
    if (!draft) return;
    if (!draft.title.trim() && !draft.brief.trim()) { setError('Add a heading or requirements before saving.'); return; }
    setSaving(true); setError(null);
    try {
      const payload = { title: draft.title, brief: draft.brief, tickets: draft.tickets, project_id: draft.project_id };
      if (draft.id) {
        const { data } = await axios.patch<{ draft: Draft }>(`/pm/drafts/${draft.id}`, payload);
        const saved = data.draft;
        setDraft({ ...saved, brief: saved.brief ?? '', tickets: normalizeLoadedTickets(saved.tickets ?? []) });
      } else {
        const { data } = await axios.post<{ draft: Draft }>('/pm/drafts', payload);
        const saved = data.draft;
        setDraft({ ...saved, brief: saved.brief ?? '', tickets: normalizeLoadedTickets(saved.tickets ?? []) });
        setOpenId(saved.id);
      }
      await load();
    } catch (e) { setError(errText(e, "Couldn't save the draft.")); }
    finally { setSaving(false); }
  }

  async function verify() {
    if (!draft?.id) { await saveDraft(); return; }
    try {
      if (draft.status === 'verified') {
        const { data } = await axios.patch<{ draft: Draft }>(`/pm/drafts/${draft.id}`, { status: 'draft', tickets: draft.tickets, title: draft.title, brief: draft.brief, project_id: draft.project_id });
        setDraft({ ...data.draft, brief: data.draft.brief ?? '', tickets: normalizeLoadedTickets(data.draft.tickets ?? []) });
      } else {
        const { data } = await axios.post<{ draft: Draft }>(`/pm/drafts/${draft.id}/verify`);
        setDraft({ ...data.draft, brief: data.draft.brief ?? '', tickets: normalizeLoadedTickets(data.draft.tickets ?? []) });
      }
      await load();
    } catch (e) { setError(errText(e, "Couldn't update verification status.")); }
  }

  async function selectOrCreateProject(): Promise<string | null> {
    if (!draft || !newProjectName.trim()) return null;
    try {
      const { data } = await axios.post<{ project: Project }>('/pm/projects', { name: newProjectName.trim(), description: '', status: 'Planning' });
      setProjects((items) => [...items, data.project]);
      setDraft((d) => d ? { ...d, project_id: data.project._id } : d);
      setNewProject(false); setNewProjectName('');
      return data.project._id;
    } catch (e) { setError(errText(e, "Couldn't create the project.")); return null; }
  }

  async function convert() {
    if (!draft?.id) { await saveDraft(); return; }
    if (!draft.project_id) { setError('Select or create a project before converting tickets.'); return; }
    setConverting(true); setError(null);
    try {
      const pending = draft.tickets.filter((t) => t.state !== 'pushed');
      if (!pending.length) { setError('All tickets are already created.'); return; }
      const results: Ticket[] = [...draft.tickets];
      for (const ticket of pending) {
        try {
          const { data } = await axios.post('/pm/brief/push', {
            projectId: draft.project_id,
            tickets: [{ title: ticket.title, description: ticket.description, level: ticket.level, estimate_hours: ticket.estimate_hours, priority: ticket.priority, assigneeId: ticket.assigneeId, dueDate: ticket.dueDate }],
          });
          const failed = Number(data?.failed || 0) > 0 || data?.results?.some((r: any) => r?.ok === false || r?.error);
          const index = results.findIndex((t) => t.uid === ticket.uid);
          if (index >= 0) results[index] = { ...results[index], state: failed ? 'failed' : 'pushed', error: failed ? (data?.results?.[0]?.error || 'Ticket creation failed.') : null };
        } catch (e) {
          const index = results.findIndex((t) => t.uid === ticket.uid);
          if (index >= 0) results[index] = { ...results[index], state: 'failed', error: errText(e, 'Ticket creation failed.') };
        }
      }
      const { data } = await axios.patch<{ draft: Draft }>(`/pm/drafts/${draft.id}`, { tickets: results, title: draft.title, brief: draft.brief, project_id: draft.project_id });
      setDraft({ ...data.draft, brief: data.draft.brief ?? '', tickets: normalizeLoadedTickets(data.draft.tickets ?? []) });
      await load();
    } catch (e) { setError(errText(e, "Couldn't convert tickets.")); }
    finally { setConverting(false); }
  }

  return <div className="rounded-lg border border-slate-200 bg-white shadow-sm">
    <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-200 px-4 py-3">
      <div><div className="text-sm font-semibold text-slate-800">Brief to tickets</div><div className="text-xs text-slate-500">Draft requirements, review tickets, then convert.</div></div>
      <button onClick={newDraft} className="rounded-md bg-slate-900 px-3 py-1.5 text-xs font-medium text-white">+ New brief</button>
    </div>
    {error && <div className="mx-4 mt-3 rounded-md border border-rose-200 bg-rose-50 px-3 py-2 text-xs text-rose-700">{error}</div>}
    <div className="divide-y divide-slate-100">
      {loading && <div className="px-4 py-6 text-center text-xs text-slate-400">Loading saved briefs…</div>}
      {!loading && !drafts.length && <div className="px-4 py-6 text-center text-xs text-slate-400">No saved briefs yet. Create one to start.</div>}
      {drafts.map((item) => <div key={item.id}>
        <button onClick={() => openDraft(item.id)} className="flex w-full items-center justify-between gap-3 px-4 py-3 text-left hover:bg-slate-50">
          <div><div className="text-sm font-medium text-slate-700">{item.title || 'Untitled brief'}</div><div className="text-[11px] text-slate-400">{item.status} · {item.pushed}/{item.total} created · {item.updated_at ? new Date(item.updated_at).toLocaleString() : 'not saved'}</div></div>
          <span className="text-xs text-slate-400">{openId === item.id ? 'Hide' : 'Open'}</span>
        </button>
        {openId === item.id && draft && <DraftEditor draft={draft} projects={projects} employees={employees} newProject={newProject} newProjectName={newProjectName} currentProject={currentProject} saving={saving} converting={converting} setDraft={setDraft} setNewProject={setNewProject} setNewProjectName={setNewProjectName} saveDraft={saveDraft} verify={verify} convert={convert} selectOrCreateProject={selectOrCreateProject} />}
      </div>)}
      {openId === 0 && draft && <DraftEditor draft={draft} projects={projects} employees={employees} newProject={newProject} newProjectName={newProjectName} currentProject={currentProject} saving={saving} converting={converting} setDraft={setDraft} setNewProject={setNewProject} setNewProjectName={setNewProjectName} saveDraft={saveDraft} verify={verify} convert={convert} selectOrCreateProject={selectOrCreateProject} />}
    </div>
  </div>;
}
