<?php

namespace App\Services\Pm;

use App\Models\PmActivity;
use App\Models\PmCard;
use App\Models\PmSubtask;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Cache;
use RuntimeException;

class TaskmanduSync
{
    private bool $baseline = false;
    public function __construct(private TaskmanduClient $client) {}
    public function configured(): bool { return $this->client->configured(); }
    public function run(): int { $employees=$this->employeeMap(); $count=0; $this->baseline=PmCard::query()->exists(); $count+=$this->syncStandaloneTasks($employees); $count+=$this->syncProjectBoards($employees); try{Cache::forever('pm.last_synced_at',now()->toIso8601String());}catch(\Throwable $e){report($e);} return $count; }
    public function employeeMap(): array { $map=[]; foreach($this->client->paginate('/employees') as $e){$name=trim(($e['firstName']??'').' '.($e['lastName']??''));foreach(['employeeId','_id','userId'] as $key)if(!empty($e[$key])&&is_string($e[$key]))$map[$e[$key]]=$name;} return $map; }
    private function names(array $employees,array $ids):?string{$names=collect($ids)->map(fn($id)=>$employees[$id]??$id)->filter();return $names->isEmpty()?null:$names->implode(', ');}
    private function syncStandaloneTasks(array $employees):int{$tasks=$this->client->paginate('/tasks');$frontend=rtrim(config('services.taskmandu.frontend_url',''),'/');foreach($tasks as $t){$card=PmCard::firstOrNew(['external_id'=>'task:'.$t['_id']]);[$existed,$oldStatus,$oldComments]=[$card->exists,$card->status,(int)$card->comments_count];$card->fill(['title'=>$t['title'],'description'=>$t['description']??null,'assignee'=>$this->names($employees,$t['assignedToId']??[]),'status'=>$t['status'],'due_at'=>$t['dueDate']??null,'last_activity_at'=>Carbon::parse($t['updatedAt']),'subtasks_count'=>0,'project_id'=>null,'project_name'=>null,'task_id'=>$t['_id'],'priority'=>$t['priority']??null,'estimated_hours'=>$t['estimatedHours']??null,'tags'=>$t['tags']??[],'comments_count'=>count($t['comments']??[]),'assigned_by'=>$t['assignedByName']??null,'url'=>$frontend?"{$frontend}/tasks/{$t['_id']}":null]);$card->save();$this->track($card,$existed,$oldStatus,$oldComments);}return count($tasks);}
    private function syncProjectBoards(array $employees):int{$projects=$this->client->paginate('/projects');$frontend=rtrim(config('services.taskmandu.frontend_url',''),'/');$count=0;$seenSubs=[];foreach($projects as $p){foreach($p['tasks']??[] as $t){$lastComment=collect($t['comments']??[])->last();$lastActivity=$lastComment['createdAt']??$t['createdAt']??null;$card=PmCard::firstOrNew(['external_id'=>"project:{$p['_id']}:task:{$t['_id']}"]);[$existed,$oldStatus,$oldComments]=[$card->exists,$card->status,(int)$card->comments_count];$card->fill(['title'=>$t['title'],'description'=>$t['description']??null,'assignee'=>$this->names($employees,$t['assignedToId']??[]),'status'=>$t['status'],'due_at'=>$t['dueDate']??null,'last_activity_at'=>$lastActivity?Carbon::parse($lastActivity):null,'subtasks_count'=>count($t['subTasks']??[]),'project_id'=>$p['_id'],'project_name'=>$p['name'],'task_id'=>$t['_id'],'priority'=>$t['priority']??null,'estimated_hours'=>$t['estimatedHours']??null,'tags'=>$t['tags']??[],'comments_count'=>count($t['comments']??[]),'assigned_by'=>$t['assignedByName']??null,'url'=>$frontend?"{$frontend}/projects/{$p['_id']}":null]);$card->save();$this->track($card,$existed,$oldStatus,$oldComments);$count++;$this->syncSubTasks($p,$t,$card,$employees,$seenSubs);}}PmSubtask::query()->whereNotIn('external_id',$seenSubs?:[''])->delete();return $count;}
    private function syncSubTasks(array $project,array $task,PmCard $parent,array $employees,array &$seen):void{$frontend=rtrim(config('services.taskmandu.frontend_url',''),'/');foreach($task['subTasks']??[] as $s){$key="project:{$project['_id']}:task:{$task['_id']}:sub:{$s['_id']}";$seen[]=$key;PmSubtask::updateOrCreate(['external_id'=>$key],['project_id'=>$project['_id'],'project_name'=>$project['name'],'task_id'=>$task['_id'],'subtask_id'=>$s['_id'],'parent_title'=>$task['title'],'parent_assignee'=>$parent->assignee,'parent_due_at'=>$task['dueDate']??null,'title'=>$s['title'],'assignee'=>$this->names($employees,$s['assignedToId']??[]),'assigned_by'=>$s['assignedByName']??null,'status'=>$s['status']??'Assigned','comments_count'=>count($s['comments']??[]),'remote_created_at'=>!empty($s['createdAt'])?Carbon::parse($s['createdAt']):null,'url'=>$frontend?"{$frontend}/projects/{$project['_id']}":null]);}}
    public function assignSubTask(PmSubtask $sub,string $employeeId):string{$this->client->patch("/projects/{$sub->project_id}/tasks/{$sub->task_id}/subtasks/{$sub->subtask_id}",['assignedToId'=>[$employeeId]]);$name=collect($this->listEmployees())->firstWhere('employeeId',$employeeId)['name']??null;return $name?:$employeeId;}
    public function createSubTask(string $projectId,string $taskId,string $title,string $assigneeEmployeeId,string $assignedByName):array{return $this->client->post("/projects/{$projectId}/tasks/{$taskId}/subtasks",['title'=>$title,'assignedToId'=>[$assigneeEmployeeId],'assignedByName'=>$assignedByName,'status'=>'Assigned']);}
    private function track(PmCard $card,bool $existed,?string $oldStatus,int $oldComments=0):void{if(!$this->baseline)return;if(!$existed)PmActivity::record('created',$card);else{if($oldStatus!==$card->status)PmActivity::record('status_change',$card,['from'=>$oldStatus,'to'=>$card->status]);if((int)$card->comments_count>$oldComments)PmActivity::record('comment',$card,['count'=>(int)$card->comments_count-$oldComments]);}}
    public function createTask(string $title,string $description,string $assigneeEmployeeId,string $dueDate,array $extra=[],string $fallbackLine=''):array{[$res,$fallback]=$this->postWithFallback('/tasks',['title'=>$title,'description'=>$description,'assignedToId'=>[$assigneeEmployeeId],'dueDate'=>$dueDate,'status'=>'Assigned'],$extra,$fallbackLine);return ['data'=>$res['data']??[],'fallback'=>$fallback];}
    public function createProjectTask(string $projectId,string $title,string $description,string $assigneeEmployeeId,string $assignedByName,string $dueDate,array $extra=[],string $fallbackLine=''):array{[$res,$fallback]=$this->postWithFallback("/projects/{$projectId}/tasks",['title'=>$title,'description'=>$description,'assignedToId'=>[$assigneeEmployeeId],'assignedByName'=>$assignedByName,'dueDate'=>$dueDate,'status'=>'Assigned'],$extra,$fallbackLine);$project=$res['data']??[];$tasks=collect($project['tasks']??[]);$task=$tasks->last(fn($t)=>($t['title']??null)===$title)??$tasks->last()??[];return ['project'=>$project,'task'=>$task,'fallback'=>$fallback];}
    private function postWithFallback(string $path,array $base,array $extra,string $fallbackLine):array{$extra=array_filter($extra,fn($v)=>$v!==null&&$v!==[]&&$v!=='');if(!$extra)return[$this->client->post($path,$base),false];try{return[$this->client->post($path,$base+$extra),false];}catch(RuntimeException $e){if(!preg_match('/\((400|422)\)/',$e->getMessage()))throw $e;$base['description']=trim(($base['description']??'')."\n\n".$fallbackLine);return[$this->client->post($path,$base),true];}}
    public function listEmployees():array{return collect($this->client->paginate('/employees'))->map(fn($e)=>['employeeId'=>$e['employeeId'],'id'=>$e['_id']??null,'name'=>trim($e['firstName'].' '.$e['lastName']),'designation'=>$e['designation']??null])->values()->all();}
}
