<?php

namespace App\Http\Controllers;

use App\Models\PmDraft;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class PmDraftController extends Controller
{
    public function index(): JsonResponse
    {
        $drafts = PmDraft::query()->latest('updated_at')->limit(50)->get()->map(fn (PmDraft $d) => $this->summary($d))->all();
        return response()->json(['drafts' => $drafts]);
    }

    public function show(PmDraft $draft): JsonResponse
    {
        return response()->json(['draft' => $this->full($draft)]);
    }

    public function store(Request $r): JsonResponse
    {
        return $this->save(new PmDraft(['created_by' => $r->user()?->name]), $r);
    }

    public function update(Request $r, PmDraft $draft): JsonResponse
    {
        return $this->save($draft, $r);
    }

    public function destroy(PmDraft $draft): JsonResponse
    {
        $draft->delete();
        return response()->json(['ok' => true]);
    }

    public function verify(PmDraft $draft): JsonResponse
    {
        $draft->update(['status' => $draft->status === 'verified' ? 'draft' : 'verified']);
        return response()->json(['draft' => $this->full($draft->fresh())]);
    }

    private function save(PmDraft $draft, Request $r): JsonResponse
    {
        $data = $r->validate([
            'title' => 'nullable|string|max:200',
            'brief' => 'nullable|string|max:8000',
            'project_id' => ['nullable', 'regex:/^[0-9a-fA-F]{24}$/'],
            'source_type' => ['nullable', Rule::in(['brief', 'meeting'])],
            'source_id' => 'nullable|integer|min:1',
            'source_title' => 'nullable|string|max:200',
            'tickets' => 'present|array|max:30',
            'tickets.*.uid' => 'required|string|max:40',
            'tickets.*.title' => 'nullable|string|max:200',
            'tickets.*.description' => 'nullable|string|max:3000',
            'tickets.*.level' => 'nullable|string|max:20',
            'tickets.*.estimate_hours' => 'nullable|numeric|min:0|max:1000',
            'tickets.*.priority' => ['nullable', Rule::in(['Low', 'Medium', 'High', 'Critical'])],
            'tickets.*.assigneeId' => 'nullable|string|max:100',
            'tickets.*.dueDate' => 'nullable|date_format:Y-m-d',
            'tickets.*.state' => ['nullable', Rule::in(['draft', 'pushed', 'failed'])],
            'tickets.*.error' => 'nullable|string|max:500',
            'tickets.*.autoGenerated' => 'nullable|boolean',
            'tickets.*.sourceIndex' => 'nullable|integer|min:0|max:1000',
        ]);

        $tickets = collect($data['tickets'])->map(fn ($t) => [
            'uid' => (string) $t['uid'],
            'title' => (string) ($t['title'] ?? ''),
            'description' => (string) ($t['description'] ?? ''),
            'level' => (string) ($t['level'] ?? 'intern'),
            'estimate_hours' => isset($t['estimate_hours']) ? (float) $t['estimate_hours'] : '',
            'priority' => $t['priority'] ?? 'Medium',
            'assigneeId' => (string) ($t['assigneeId'] ?? ''),
            'dueDate' => (string) ($t['dueDate'] ?? ''),
            'state' => $t['state'] ?? 'draft',
            'error' => $t['error'] ?? null,
            'autoGenerated' => (bool) ($t['autoGenerated'] ?? false),
            'sourceIndex' => array_key_exists('sourceIndex', $t) && $t['sourceIndex'] !== null ? (int) $t['sourceIndex'] : null,
        ])->values()->all();

        $pushed = collect($tickets)->where('state', 'pushed')->count();
        $status = $tickets === [] || $pushed === 0 ? 'draft' : ($pushed === count($tickets) ? 'pushed' : 'partial');

        $draft->fill([
            'title' => $this->titleFor($data['title'] ?? null, $data['brief'] ?? null, $draft),
            'brief' => $data['brief'] ?? null,
            'project_id' => $data['project_id'] ?? null,
            'source_type' => $data['source_type'] ?? 'brief',
            'source_id' => $data['source_id'] ?? null,
            'source_title' => $data['source_title'] ?? null,
            'tickets' => $tickets,
            'status' => $status,
        ])->save();

        return response()->json(['draft' => $this->full($draft->fresh())]);
    }

    private function titleFor(?string $title, ?string $brief, PmDraft $draft): string
    {
        if (filled($title)) return mb_substr(trim($title), 0, 200);
        if ($draft->exists && filled($draft->title) && $draft->title !== 'Untitled draft') return $draft->title;
        $first = collect(preg_split('/\R/', (string) $brief))->map(fn ($l) => trim((string) $l))->first(fn ($l) => $l !== '');
        return $first ? mb_substr(ltrim($first, "-*#• \t"), 0, 80) : 'Untitled draft';
    }

    private function summary(PmDraft $d): array
    {
        $tickets = $d->tickets ?? [];
        return [
            'id' => $d->id,
            'title' => $d->title,
            'status' => $d->status,
            'total' => count($tickets),
            'pushed' => collect($tickets)->where('state', 'pushed')->count(),
            'project_id' => $d->project_id,
            'updated_at' => $d->updated_at?->toIso8601String(),
            'source_type' => $d->source_type ?? 'brief',
            'source_id' => $d->source_id,
            'source_title' => $d->source_title,
        ];
    }

    private function full(PmDraft $d): array
    {
        return $this->summary($d) + ['brief' => (string) $d->brief, 'tickets' => $d->tickets ?? []];
    }
}
